# sync_admin.ps1
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

function Read-FileUtf8 {
    param([string]$path)
    if (Test-Path $path) {
        return [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
    }
    return ""
}

function To-JsonString {
    param([string]$s)
    $s = $s.Replace('\', '\\')
    $s = $s.Replace('"', '\"')
    $s = $s.Replace("`r`n", '\n')
    $s = $s.Replace("`n", '\n')
    $s = $s.Replace("`r", '\n')
    $s = $s.Replace("`t", '\t')
    return $s
}

# Read core files
$bib = Read-FileUtf8 (Join-Path $root "_bibliography\papers.bib")
$resumeEn = Read-FileUtf8 (Join-Path $root "assets\json\resume.json")
$resumeZh = Read-FileUtf8 (Join-Path $root "assets\json\resume_zh.json")
$aboutEn = Read-FileUtf8 (Join-Path $root "_pages\about.md")
$aboutZh = Read-FileUtf8 (Join-Path $root "ch\index.md")

# Read all news files
$newsArr = @()
$newsDir = Join-Path $root "_news"
if (Test-Path $newsDir) {
    Get-ChildItem (Join-Path $newsDir "*.md") | ForEach-Object {
        $content = [System.IO.File]::ReadAllText($_.FullName, [System.Text.Encoding]::UTF8)
        $newsArr += [PSCustomObject]@{ name = $_.Name; content = $content }
    }
}
$newsJson = ConvertTo-Json $newsArr -Depth 3 -Compress
if (-not $newsJson -or $newsJson -eq "null") { $newsJson = "[]" }

# Read all project files
$projArr = @()
$projDir = Join-Path $root "_projects"
if (Test-Path $projDir) {
    Get-ChildItem (Join-Path $projDir "*.md") | ForEach-Object {
        $content = [System.IO.File]::ReadAllText($_.FullName, [System.Text.Encoding]::UTF8)
        $projArr += [PSCustomObject]@{ name = $_.Name; content = $content }
    }
}
$projJson = ConvertTo-Json $projArr -Depth 3 -Compress
if (-not $projJson -or $projJson -eq "null") { $projJson = "[]" }

# Read all intro files (for publications)
$introArr = @()
$introDir = Join-Path $root "_includes\intros"
if (Test-Path $introDir) {
    Get-ChildItem (Join-Path $introDir "*.md") | ForEach-Object {
        $content = [System.IO.File]::ReadAllText($_.FullName, [System.Text.Encoding]::UTF8)
        $introArr += [PSCustomObject]@{ name = $_.Name; content = $content }
    }
}
$introJson = ConvertTo-Json $introArr -Depth 3 -Compress
if (-not $introJson -or $introJson -eq "null") { $introJson = "[]" }

# Escape for JS strings
$bibJ = To-JsonString $bib
$aboutEnJ = To-JsonString $aboutEn
$aboutZhJ = To-JsonString $aboutZh

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Build admin_data.js
$lines = @()
$lines += "// Auto-generated by sync_admin.ps1 at $timestamp"
$lines += "window.PRELOADED_RAW = {"
$lines += "  bib: ""$bibJ"","
$lines += "  resume_en: $resumeEn,"
$lines += "  resume_zh: $resumeZh,"
$lines += "  about_en: ""$aboutEnJ"","
$lines += "  about_zh: ""$aboutZhJ"","
$lines += "  news: $newsJson,"
$lines += "  projects: $projJson,"
$lines += "  intros: $introJson"
$lines += "};"

$outputPath = Join-Path $root "admin_data.js"
$jsContent = $lines -join "`r`n"
[System.IO.File]::WriteAllText($outputPath, $jsContent, [System.Text.Encoding]::UTF8)

Write-Host ""
Write-Host "  =============================="  -ForegroundColor Cyan
Write-Host "  admin_data.js generated!"  -ForegroundColor Green
Write-Host "  Time: $timestamp"  -ForegroundColor Gray
Write-Host "  News: $($newsArr.Count) files"  -ForegroundColor Gray
Write-Host "  Projects: $($projArr.Count) files"  -ForegroundColor Gray
Write-Host "  =============================="  -ForegroundColor Cyan
Write-Host ""
Write-Host "  Opening admin panel..."  -ForegroundColor Yellow

Start-Process (Join-Path $root "admin.html")
